refonte readme
calculquebec/pennylane-calculquebec pull request #48
Opened 2024-12-18 18:02 UTC by boucherlfg

- change texts to better represent current plugin alignments
- add table of contents
- add reference to the Wiki and other docs
- change project structure picture
- change pennylane_snowflurry to pennylane_calculquebec

2024-12-18 18:10 UTC, Scirelgar commented on README.md
> +![prject_structure](./doc/assets/project_structure.png)
plutôt utiliser le lien https://raw.githubusercontent.com/calculquebec/pennylane-calculquebec/refs/heads/feature/update_readme/doc/assets/project_structure.png

t'as ce lien en cliquant là-dessus, sans ça l'image ne suit pas sur PyPI puisque PyPI n'a pas accès au repos
![image](https://github.com/user-attachments/assets/8acbd783-19cb-498d-ab78-c6d7ad869c37)

2024-12-18 20:48 UTC, Scirelgar requested changes
Quelques changements (voir commentaires), overall tres bien!

2024-12-18 20:48 UTC, Scirelgar commented on README.md
> +As of version 0.3.0, --there is no need to install Julia manually--, since the plugin will download and install the required version automatically upon first use. This Julia environment is bound to t
Qu'est-ce que le -- fait? Je crois que ** ** va mettre en gras non?

2024-12-18 20:48 UTC, Scirelgar commented on README.md
> +--To ensure this correct configuration, during the installation process, the checkbox `Add Julia to PATH` must be checked.--
Même chose ici

2024-12-18 20:48 UTC, Scirelgar commented on README.md
> +As of version 0.5.0, --Julia will only be installed if you use Snowflurry.Qubit--. You can use Monarq.Default without depending on Julia.
Même chose ici

2024-12-18 20:48 UTC, Scirelgar commented on README.md
> +![prject_structure]([./doc/assets/project_structure.png](https://github.com/calculquebec/pennylane-calculquebec/blob/feature/update_readme/doc/assets/project_structure.png))
My bad, j'étais pas clair, ça prend vraiment le raw.githubusercontent.com, autrement l'image ne render pas sur PyPI.

`![project_structure](https://raw.githubusercontent.com/calculquebec/pennylane-calculquebec/9276a260959c886eed87373b74090a9d652b130c/doc/assets/project_structure.png)`

2024-12-18 20:48 UTC, Scirelgar commented on README.md
> +The plugin is currently in its beta phase and provides access to MonarQ directly through API calls. It also contains capabilities for obtaining benchmarks and machine informations. There are alsu fea
> there are also*

2024-12-19 14:35 UTC, boucherlfg commented on README.md
> +As of version 0.3.0, --there is no need to install Julia manually--, since the plugin will download and install the required version automatically upon first use. This Julia environment is bound to t
Je sais même pas comment le -- s'est ramassé là

2024-12-19 14:40 UTC, Scirelgar approved these changes
LGTM!

2024-12-19 14:59 UTC, merged